/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewProjectIdRouteImport } from './routes/preview.$projectId'
import { Route as ApiAiDesignChatRouteImport } from './routes/api/ai-design-chat'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthFigmaStartRouteImport } from './routes/auth/figma.start'
import { Route as AuthFigmaCallbackRouteImport } from './routes/auth/figma.callback'
import { Route as ApiFigmaImportRouteImport } from './routes/api/figma.import'
import { Route as ApiFigmaDisconnectRouteImport } from './routes/api/figma.disconnect'
import { Route as AuthenticatedProjectsIdPreviewRouteImport } from './routes/_authenticated/projects/$id/preview'
import { Route as AuthenticatedProjectsIdEditorRouteImport } from './routes/_authenticated/projects/$id/editor'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectIdRoute = PreviewProjectIdRouteImport.update({
  id: '/preview/$projectId',
  path: '/preview/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDesignChatRoute = ApiAiDesignChatRouteImport.update({
  id: '/api/ai-design-chat',
  path: '/api/ai-design-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthFigmaStartRoute = AuthFigmaStartRouteImport.update({
  id: '/auth/figma/start',
  path: '/auth/figma/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFigmaCallbackRoute = AuthFigmaCallbackRouteImport.update({
  id: '/auth/figma/callback',
  path: '/auth/figma/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaImportRoute = ApiFigmaImportRouteImport.update({
  id: '/api/figma/import',
  path: '/api/figma/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaDisconnectRoute = ApiFigmaDisconnectRouteImport.update({
  id: '/api/figma/disconnect',
  path: '/api/figma/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdPreviewRoute =
  AuthenticatedProjectsIdPreviewRouteImport.update({
    id: '/projects/$id/preview',
    path: '/projects/$id/preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdEditorRoute =
  AuthenticatedProjectsIdEditorRouteImport.update({
    id: '/projects/$id/editor',
    path: '/projects/$id/editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/preview/$projectId': typeof PreviewProjectIdRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/_authenticated/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/_authenticated/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/api/ai-design-chat'
    | '/preview/$projectId'
    | '/api/figma/disconnect'
    | '/api/figma/import'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/projects/$id/editor'
    | '/projects/$id/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/api/ai-design-chat'
    | '/preview/$projectId'
    | '/api/figma/disconnect'
    | '/api/figma/import'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/projects/$id/editor'
    | '/projects/$id/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/upload'
    | '/api/ai-design-chat'
    | '/preview/$projectId'
    | '/api/figma/disconnect'
    | '/api/figma/import'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/_authenticated/projects/$id/editor'
    | '/_authenticated/projects/$id/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ApiAiDesignChatRoute: typeof ApiAiDesignChatRoute
  PreviewProjectIdRoute: typeof PreviewProjectIdRoute
  ApiFigmaDisconnectRoute: typeof ApiFigmaDisconnectRoute
  ApiFigmaImportRoute: typeof ApiFigmaImportRoute
  AuthFigmaCallbackRoute: typeof AuthFigmaCallbackRoute
  AuthFigmaStartRoute: typeof AuthFigmaStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$projectId': {
      id: '/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/preview/$projectId'
      preLoaderRoute: typeof PreviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-design-chat': {
      id: '/api/ai-design-chat'
      path: '/api/ai-design-chat'
      fullPath: '/api/ai-design-chat'
      preLoaderRoute: typeof ApiAiDesignChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/figma/start': {
      id: '/auth/figma/start'
      path: '/auth/figma/start'
      fullPath: '/auth/figma/start'
      preLoaderRoute: typeof AuthFigmaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/figma/callback': {
      id: '/auth/figma/callback'
      path: '/auth/figma/callback'
      fullPath: '/auth/figma/callback'
      preLoaderRoute: typeof AuthFigmaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/import': {
      id: '/api/figma/import'
      path: '/api/figma/import'
      fullPath: '/api/figma/import'
      preLoaderRoute: typeof ApiFigmaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/disconnect': {
      id: '/api/figma/disconnect'
      path: '/api/figma/disconnect'
      fullPath: '/api/figma/disconnect'
      preLoaderRoute: typeof ApiFigmaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id/preview': {
      id: '/_authenticated/projects/$id/preview'
      path: '/projects/$id/preview'
      fullPath: '/projects/$id/preview'
      preLoaderRoute: typeof AuthenticatedProjectsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/editor': {
      id: '/_authenticated/projects/$id/editor'
      path: '/projects/$id/editor'
      fullPath: '/projects/$id/editor'
      preLoaderRoute: typeof AuthenticatedProjectsIdEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedProjectsIdEditorRoute: typeof AuthenticatedProjectsIdEditorRoute
  AuthenticatedProjectsIdPreviewRoute: typeof AuthenticatedProjectsIdPreviewRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedProjectsIdEditorRoute: AuthenticatedProjectsIdEditorRoute,
  AuthenticatedProjectsIdPreviewRoute: AuthenticatedProjectsIdPreviewRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ApiAiDesignChatRoute: ApiAiDesignChatRoute,
  PreviewProjectIdRoute: PreviewProjectIdRoute,
  ApiFigmaDisconnectRoute: ApiFigmaDisconnectRoute,
  ApiFigmaImportRoute: ApiFigmaImportRoute,
  AuthFigmaCallbackRoute: AuthFigmaCallbackRoute,
  AuthFigmaStartRoute: AuthFigmaStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
