/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CanvasEditorRouteImport } from './routes/canvas-editor'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PreviewProjectIdRouteImport } from './routes/preview.$projectId'
import { Route as ApiAiPuckEditRouteImport } from './routes/api/ai-puck-edit'
import { Route as ApiAiDesignChatRouteImport } from './routes/api/ai-design-chat'
import { Route as AuthenticatedUploadRouteImport } from './routes/_authenticated/upload'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as PreviewProjectIdPageSlugRouteImport } from './routes/preview.$projectId.$pageSlug'
import { Route as AuthFigmaStartRouteImport } from './routes/auth/figma.start'
import { Route as AuthFigmaCallbackRouteImport } from './routes/auth/figma.callback'
import { Route as ApiPublicFigmaDiagnosticRouteImport } from './routes/api/public/figma-diagnostic'
import { Route as ApiFigmaRenderRouteImport } from './routes/api/figma.render'
import { Route as ApiFigmaProcessAssetsRouteImport } from './routes/api/figma.process-assets'
import { Route as ApiFigmaImportRouteImport } from './routes/api/figma.import'
import { Route as ApiFigmaFetchNodeRouteImport } from './routes/api/figma.fetch-node'
import { Route as ApiFigmaDisconnectRouteImport } from './routes/api/figma.disconnect'
import { Route as ApiFigmaConvertBatchRouteImport } from './routes/api/figma.convert-batch'
import { Route as ApiFigmaConvertRouteImport } from './routes/api/figma.convert'
import { Route as ApiFigmaCleanupRouteImport } from './routes/api/figma.cleanup'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedProjectsIdPuckEditorRouteImport } from './routes/_authenticated/projects/$id/puck-editor'
import { Route as AuthenticatedProjectsIdPreviewRouteImport } from './routes/_authenticated/projects/$id/preview'
import { Route as AuthenticatedProjectsIdEditorRouteImport } from './routes/_authenticated/projects/$id/editor'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasEditorRoute = CanvasEditorRouteImport.update({
  id: '/canvas-editor',
  path: '/canvas-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewProjectIdRoute = PreviewProjectIdRouteImport.update({
  id: '/preview/$projectId',
  path: '/preview/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPuckEditRoute = ApiAiPuckEditRouteImport.update({
  id: '/api/ai-puck-edit',
  path: '/api/ai-puck-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDesignChatRoute = ApiAiDesignChatRouteImport.update({
  id: '/api/ai-design-chat',
  path: '/api/ai-design-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUploadRoute = AuthenticatedUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const PreviewProjectIdPageSlugRoute =
  PreviewProjectIdPageSlugRouteImport.update({
    id: '/$pageSlug',
    path: '/$pageSlug',
    getParentRoute: () => PreviewProjectIdRoute,
  } as any)
const AuthFigmaStartRoute = AuthFigmaStartRouteImport.update({
  id: '/auth/figma/start',
  path: '/auth/figma/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFigmaCallbackRoute = AuthFigmaCallbackRouteImport.update({
  id: '/auth/figma/callback',
  path: '/auth/figma/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFigmaDiagnosticRoute =
  ApiPublicFigmaDiagnosticRouteImport.update({
    id: '/api/public/figma-diagnostic',
    path: '/api/public/figma-diagnostic',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiFigmaRenderRoute = ApiFigmaRenderRouteImport.update({
  id: '/api/figma/render',
  path: '/api/figma/render',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaProcessAssetsRoute = ApiFigmaProcessAssetsRouteImport.update({
  id: '/api/figma/process-assets',
  path: '/api/figma/process-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaImportRoute = ApiFigmaImportRouteImport.update({
  id: '/api/figma/import',
  path: '/api/figma/import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaFetchNodeRoute = ApiFigmaFetchNodeRouteImport.update({
  id: '/api/figma/fetch-node',
  path: '/api/figma/fetch-node',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaDisconnectRoute = ApiFigmaDisconnectRouteImport.update({
  id: '/api/figma/disconnect',
  path: '/api/figma/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaConvertBatchRoute = ApiFigmaConvertBatchRouteImport.update({
  id: '/api/figma/convert-batch',
  path: '/api/figma/convert-batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaConvertRoute = ApiFigmaConvertRouteImport.update({
  id: '/api/figma/convert',
  path: '/api/figma/convert',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFigmaCleanupRoute = ApiFigmaCleanupRouteImport.update({
  id: '/api/figma/cleanup',
  path: '/api/figma/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdPuckEditorRoute =
  AuthenticatedProjectsIdPuckEditorRouteImport.update({
    id: '/projects/$id/puck-editor',
    path: '/projects/$id/puck-editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdPreviewRoute =
  AuthenticatedProjectsIdPreviewRouteImport.update({
    id: '/projects/$id/preview',
    path: '/projects/$id/preview',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIdEditorRoute =
  AuthenticatedProjectsIdEditorRouteImport.update({
    id: '/projects/$id/editor',
    path: '/projects/$id/editor',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canvas-editor': typeof CanvasEditorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/api/ai-puck-edit': typeof ApiAiPuckEditRoute
  '/preview/$projectId': typeof PreviewProjectIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/figma/cleanup': typeof ApiFigmaCleanupRoute
  '/api/figma/convert': typeof ApiFigmaConvertRoute
  '/api/figma/convert-batch': typeof ApiFigmaConvertBatchRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/fetch-node': typeof ApiFigmaFetchNodeRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/api/figma/process-assets': typeof ApiFigmaProcessAssetsRoute
  '/api/figma/render': typeof ApiFigmaRenderRoute
  '/api/public/figma-diagnostic': typeof ApiPublicFigmaDiagnosticRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/preview/$projectId/$pageSlug': typeof PreviewProjectIdPageSlugRoute
  '/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
  '/projects/$id/puck-editor': typeof AuthenticatedProjectsIdPuckEditorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canvas-editor': typeof CanvasEditorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/api/ai-puck-edit': typeof ApiAiPuckEditRoute
  '/preview/$projectId': typeof PreviewProjectIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/figma/cleanup': typeof ApiFigmaCleanupRoute
  '/api/figma/convert': typeof ApiFigmaConvertRoute
  '/api/figma/convert-batch': typeof ApiFigmaConvertBatchRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/fetch-node': typeof ApiFigmaFetchNodeRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/api/figma/process-assets': typeof ApiFigmaProcessAssetsRoute
  '/api/figma/render': typeof ApiFigmaRenderRoute
  '/api/public/figma-diagnostic': typeof ApiPublicFigmaDiagnosticRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/preview/$projectId/$pageSlug': typeof PreviewProjectIdPageSlugRoute
  '/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
  '/projects/$id/puck-editor': typeof AuthenticatedProjectsIdPuckEditorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/canvas-editor': typeof CanvasEditorRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/onboarding': typeof OnboardingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/upload': typeof AuthenticatedUploadRoute
  '/api/ai-design-chat': typeof ApiAiDesignChatRoute
  '/api/ai-puck-edit': typeof ApiAiPuckEditRoute
  '/preview/$projectId': typeof PreviewProjectIdRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/figma/cleanup': typeof ApiFigmaCleanupRoute
  '/api/figma/convert': typeof ApiFigmaConvertRoute
  '/api/figma/convert-batch': typeof ApiFigmaConvertBatchRoute
  '/api/figma/disconnect': typeof ApiFigmaDisconnectRoute
  '/api/figma/fetch-node': typeof ApiFigmaFetchNodeRoute
  '/api/figma/import': typeof ApiFigmaImportRoute
  '/api/figma/process-assets': typeof ApiFigmaProcessAssetsRoute
  '/api/figma/render': typeof ApiFigmaRenderRoute
  '/api/public/figma-diagnostic': typeof ApiPublicFigmaDiagnosticRoute
  '/auth/figma/callback': typeof AuthFigmaCallbackRoute
  '/auth/figma/start': typeof AuthFigmaStartRoute
  '/preview/$projectId/$pageSlug': typeof PreviewProjectIdPageSlugRoute
  '/_authenticated/projects/$id/editor': typeof AuthenticatedProjectsIdEditorRoute
  '/_authenticated/projects/$id/preview': typeof AuthenticatedProjectsIdPreviewRoute
  '/_authenticated/projects/$id/puck-editor': typeof AuthenticatedProjectsIdPuckEditorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canvas-editor'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/api/ai-design-chat'
    | '/api/ai-puck-edit'
    | '/preview/$projectId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/figma/cleanup'
    | '/api/figma/convert'
    | '/api/figma/convert-batch'
    | '/api/figma/disconnect'
    | '/api/figma/fetch-node'
    | '/api/figma/import'
    | '/api/figma/process-assets'
    | '/api/figma/render'
    | '/api/public/figma-diagnostic'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/preview/$projectId/$pageSlug'
    | '/projects/$id/editor'
    | '/projects/$id/preview'
    | '/projects/$id/puck-editor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canvas-editor'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/upload'
    | '/api/ai-design-chat'
    | '/api/ai-puck-edit'
    | '/preview/$projectId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/figma/cleanup'
    | '/api/figma/convert'
    | '/api/figma/convert-batch'
    | '/api/figma/disconnect'
    | '/api/figma/fetch-node'
    | '/api/figma/import'
    | '/api/figma/process-assets'
    | '/api/figma/render'
    | '/api/public/figma-diagnostic'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/preview/$projectId/$pageSlug'
    | '/projects/$id/editor'
    | '/projects/$id/preview'
    | '/projects/$id/puck-editor'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/canvas-editor'
    | '/login'
    | '/mcp'
    | '/onboarding'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/upload'
    | '/api/ai-design-chat'
    | '/api/ai-puck-edit'
    | '/preview/$projectId'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/figma/cleanup'
    | '/api/figma/convert'
    | '/api/figma/convert-batch'
    | '/api/figma/disconnect'
    | '/api/figma/fetch-node'
    | '/api/figma/import'
    | '/api/figma/process-assets'
    | '/api/figma/render'
    | '/api/public/figma-diagnostic'
    | '/auth/figma/callback'
    | '/auth/figma/start'
    | '/preview/$projectId/$pageSlug'
    | '/_authenticated/projects/$id/editor'
    | '/_authenticated/projects/$id/preview'
    | '/_authenticated/projects/$id/puck-editor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CanvasEditorRoute: typeof CanvasEditorRoute
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  OnboardingRoute: typeof OnboardingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAiDesignChatRoute: typeof ApiAiDesignChatRoute
  ApiAiPuckEditRoute: typeof ApiAiPuckEditRoute
  PreviewProjectIdRoute: typeof PreviewProjectIdRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiFigmaCleanupRoute: typeof ApiFigmaCleanupRoute
  ApiFigmaConvertRoute: typeof ApiFigmaConvertRoute
  ApiFigmaConvertBatchRoute: typeof ApiFigmaConvertBatchRoute
  ApiFigmaDisconnectRoute: typeof ApiFigmaDisconnectRoute
  ApiFigmaFetchNodeRoute: typeof ApiFigmaFetchNodeRoute
  ApiFigmaImportRoute: typeof ApiFigmaImportRoute
  ApiFigmaProcessAssetsRoute: typeof ApiFigmaProcessAssetsRoute
  ApiFigmaRenderRoute: typeof ApiFigmaRenderRoute
  ApiPublicFigmaDiagnosticRoute: typeof ApiPublicFigmaDiagnosticRoute
  AuthFigmaCallbackRoute: typeof AuthFigmaCallbackRoute
  AuthFigmaStartRoute: typeof AuthFigmaStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas-editor': {
      id: '/canvas-editor'
      path: '/canvas-editor'
      fullPath: '/canvas-editor'
      preLoaderRoute: typeof CanvasEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$projectId': {
      id: '/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/preview/$projectId'
      preLoaderRoute: typeof PreviewProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-puck-edit': {
      id: '/api/ai-puck-edit'
      path: '/api/ai-puck-edit'
      fullPath: '/api/ai-puck-edit'
      preLoaderRoute: typeof ApiAiPuckEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-design-chat': {
      id: '/api/ai-design-chat'
      path: '/api/ai-design-chat'
      fullPath: '/api/ai-design-chat'
      preLoaderRoute: typeof ApiAiDesignChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/upload': {
      id: '/_authenticated/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof AuthenticatedUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$projectId/$pageSlug': {
      id: '/preview/$projectId/$pageSlug'
      path: '/$pageSlug'
      fullPath: '/preview/$projectId/$pageSlug'
      preLoaderRoute: typeof PreviewProjectIdPageSlugRouteImport
      parentRoute: typeof PreviewProjectIdRoute
    }
    '/auth/figma/start': {
      id: '/auth/figma/start'
      path: '/auth/figma/start'
      fullPath: '/auth/figma/start'
      preLoaderRoute: typeof AuthFigmaStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/figma/callback': {
      id: '/auth/figma/callback'
      path: '/auth/figma/callback'
      fullPath: '/auth/figma/callback'
      preLoaderRoute: typeof AuthFigmaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/figma-diagnostic': {
      id: '/api/public/figma-diagnostic'
      path: '/api/public/figma-diagnostic'
      fullPath: '/api/public/figma-diagnostic'
      preLoaderRoute: typeof ApiPublicFigmaDiagnosticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/render': {
      id: '/api/figma/render'
      path: '/api/figma/render'
      fullPath: '/api/figma/render'
      preLoaderRoute: typeof ApiFigmaRenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/process-assets': {
      id: '/api/figma/process-assets'
      path: '/api/figma/process-assets'
      fullPath: '/api/figma/process-assets'
      preLoaderRoute: typeof ApiFigmaProcessAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/import': {
      id: '/api/figma/import'
      path: '/api/figma/import'
      fullPath: '/api/figma/import'
      preLoaderRoute: typeof ApiFigmaImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/fetch-node': {
      id: '/api/figma/fetch-node'
      path: '/api/figma/fetch-node'
      fullPath: '/api/figma/fetch-node'
      preLoaderRoute: typeof ApiFigmaFetchNodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/disconnect': {
      id: '/api/figma/disconnect'
      path: '/api/figma/disconnect'
      fullPath: '/api/figma/disconnect'
      preLoaderRoute: typeof ApiFigmaDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/convert-batch': {
      id: '/api/figma/convert-batch'
      path: '/api/figma/convert-batch'
      fullPath: '/api/figma/convert-batch'
      preLoaderRoute: typeof ApiFigmaConvertBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/convert': {
      id: '/api/figma/convert'
      path: '/api/figma/convert'
      fullPath: '/api/figma/convert'
      preLoaderRoute: typeof ApiFigmaConvertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/figma/cleanup': {
      id: '/api/figma/cleanup'
      path: '/api/figma/cleanup'
      fullPath: '/api/figma/cleanup'
      preLoaderRoute: typeof ApiFigmaCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id/puck-editor': {
      id: '/_authenticated/projects/$id/puck-editor'
      path: '/projects/$id/puck-editor'
      fullPath: '/projects/$id/puck-editor'
      preLoaderRoute: typeof AuthenticatedProjectsIdPuckEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/preview': {
      id: '/_authenticated/projects/$id/preview'
      path: '/projects/$id/preview'
      fullPath: '/projects/$id/preview'
      preLoaderRoute: typeof AuthenticatedProjectsIdPreviewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/$id/editor': {
      id: '/_authenticated/projects/$id/editor'
      path: '/projects/$id/editor'
      fullPath: '/projects/$id/editor'
      preLoaderRoute: typeof AuthenticatedProjectsIdEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedUploadRoute: typeof AuthenticatedUploadRoute
  AuthenticatedProjectsIdEditorRoute: typeof AuthenticatedProjectsIdEditorRoute
  AuthenticatedProjectsIdPreviewRoute: typeof AuthenticatedProjectsIdPreviewRoute
  AuthenticatedProjectsIdPuckEditorRoute: typeof AuthenticatedProjectsIdPuckEditorRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedUploadRoute: AuthenticatedUploadRoute,
  AuthenticatedProjectsIdEditorRoute: AuthenticatedProjectsIdEditorRoute,
  AuthenticatedProjectsIdPreviewRoute: AuthenticatedProjectsIdPreviewRoute,
  AuthenticatedProjectsIdPuckEditorRoute:
    AuthenticatedProjectsIdPuckEditorRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PreviewProjectIdRouteChildren {
  PreviewProjectIdPageSlugRoute: typeof PreviewProjectIdPageSlugRoute
}

const PreviewProjectIdRouteChildren: PreviewProjectIdRouteChildren = {
  PreviewProjectIdPageSlugRoute: PreviewProjectIdPageSlugRoute,
}

const PreviewProjectIdRouteWithChildren =
  PreviewProjectIdRoute._addFileChildren(PreviewProjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CanvasEditorRoute: CanvasEditorRoute,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  OnboardingRoute: OnboardingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAiDesignChatRoute: ApiAiDesignChatRoute,
  ApiAiPuckEditRoute: ApiAiPuckEditRoute,
  PreviewProjectIdRoute: PreviewProjectIdRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiFigmaCleanupRoute: ApiFigmaCleanupRoute,
  ApiFigmaConvertRoute: ApiFigmaConvertRoute,
  ApiFigmaConvertBatchRoute: ApiFigmaConvertBatchRoute,
  ApiFigmaDisconnectRoute: ApiFigmaDisconnectRoute,
  ApiFigmaFetchNodeRoute: ApiFigmaFetchNodeRoute,
  ApiFigmaImportRoute: ApiFigmaImportRoute,
  ApiFigmaProcessAssetsRoute: ApiFigmaProcessAssetsRoute,
  ApiFigmaRenderRoute: ApiFigmaRenderRoute,
  ApiPublicFigmaDiagnosticRoute: ApiPublicFigmaDiagnosticRoute,
  AuthFigmaCallbackRoute: AuthFigmaCallbackRoute,
  AuthFigmaStartRoute: AuthFigmaStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
